# Generated by Django 5.0.7 on 2025-05-07 09:33

import dressapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dressapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("price", models.FloatField()),
                ("digital", models.BooleanField(default=False, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=dressapp.models.getFileName
                    ),
                ),
            ],
        ),
    ]
