# Generated by Django 5.0.4 on 2025-06-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dressapp", "0002_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tagline",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
