# Generated by Django 5.0.7 on 2025-05-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dressapp", "0002_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="product",
            new_name="Product",
        ),
    ]
