# Generated by Django 5.0.4 on 2025-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dressapp", "0003_rename_product_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
