# Generated by Django 5.0.4 on 2025-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dressapp", "0004_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
