# Generated by Django 5.0.4 on 2025-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dressapp", "0004_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
