# Generated by Django 5.0.4 on 2025-06-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dressapp", "0005_alter_product_category_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
