# Generated by Django 5.0.4 on 2025-06-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dressapp", "0006_shippingaddress_first_name_shippingaddress_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
