# Generated by Django 5.0.4 on 2025-06-13 11:57

import django.db.models.deletion
import dressapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dressapp", "0007_banner_featuredcategory_instagramimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=dressapp.models.getFileName)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dressapp.product",
                    ),
                ),
            ],
        ),
    ]
