# Generated by Django 5.0.4 on 2025-06-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dressapp", "0007_alter_shippingaddress_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
